#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/database
- name: Run database
  docker_container:
    name: my-db
    image: mathispappo/tp-devops-database
    networks:
      - name: my_network
    
    