#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/application
- name: Run application
  docker_container:
    name: my-api
    image: mathispappo/tp-devops-simple-api
    networks:
      - name: my_network
