#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/reverse-proxy
- name: Run reverse-proxy
  docker_container:
    name: my-reverse-proxy
    image: mathispappo/tp-devops-httpd
    networks:
      - name: my_network
    ports:
      - "80:80"